version: "2"
services:
  didauthservice:
    build: .
    image: didauthservice
    ports:
      - "127.0.0.1:8781:8781"
    command: "python DidAuthService.py"
    restart: always
    environment:
      - WHOAMI=did:dom:Exgfmw6A5RLWWeJX2G4czjLJb8yDxM
      - MY_PRIVATE_KEY=z8ne6htdQaJkE7aaEPvTGZXNt7HDaxjPrgHhTWEX1gnq6ea7vo1WQLMRqfUBws3JZmBgA916aaPic9zcpgUfUZf
      - PORT=8781
    volumes:
      - $PWD:/usr/src/app
    network_mode: host
